export type { TColor } from './color'
export type { IUser } from './user'
export type { ICategory } from './categories'
export type { ICourse } from './course'
export type { IRouteError } from './route-error.ts'
export type { IInput } from './input'
